  <!--banner section START -->
<section class="p-0 d-flex justify-content-center align-items-center mb-4" style="background-image: url('https://media.istockphoto.com/photos/young-man-arms-outstretched-by-the-sea-at-sunrise-enjoying-freedom-picture-id1285301614?b=1&k=20&m=1285301614&s=170667a&w=0&h=tDEC2-p91cZiNU5C19sVhB9L08PmaH5wIijCvRDalCI=');background-position: center;background-repeat: no-repeat; background-size: cover; height: 457px;">
        <div class="d-flex justify-content-center align-items-center card-body">
            <div class="card-title px-4" style="width: 50%; height: 220px; background-color: rgb(0,0,0, 0.5); color: #fff; border-radius: 10px;" >
                <h3 class="text-center mt-5">Welcome to Afrib Travel Stories</h3>
                <p class="mt-3 text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, tempore.</p>
                <p class="d-flex justify-content-center">
                    <a class="btn btn-primary btn-sm" href="{{route('register')}}">Get started</a>
                </p>
                <br>
            </div>
        </div>
    </section>
        <!--banner section END -->
        <section class="mt-3">
            <center><?php echo $description ?></center>
        </section>
