<?php
    if(isset($_GET['story'])){
		if(!empty($_GET['story'])){
			//get user from model
			$story = getSingleStory($_GET['story'])[0];
			//fetch story from model function getstories
			// $stories = getStories($user['id']);
		}
	}

    $user = checkAccess($story['user_id']);

?>

<div class="row">
    <div class="col-md-3">
        <div class="card mt-3">
            <div class="card-header">
                <h5 class="card-title">All Category</h5>
                <small class="text-muted">Total number of story in a category on the right</small>
            </div>

            <div class="card-body">
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                        All Categories
                    </a>
                    <?php foreach($categories = getAllCategories() as $category) : ?>
                        <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <?php echo $category['name'] ?>
                            <span class="badge badge-primary badge-pill">
                                <?php echo count(getstorybyCategory($category['id'])) ; ?>
                            </span>
                        </a>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <h5 class="card-title">All Locations</h5>
                <small class="text-muted">See stories about a location</small>
            </div>

            <div class="card-body">
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                        All Locations
                    </a>
                    <?php foreach($locations = getAllLocations() as $location) : ?>
                        <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <?php echo $location['country'] ?>
                            <span class="badge badge-primary badge-pill">
                                <?php echo count(getstorybylocation($location['id']) ); ?>

                            </span>
                        </a>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-9">
    <div class="card mt-3">
          <div class="card-body">
            <div class="card">
                <img class="card-img-top" src="<?php echo $story['image']; ?>" alt="Card image cap">
                <div class="card-body">
                  <h3 class="card-title text-center"><?php echo $story['title']; ?></h3>
                  <br>
                  <div class="card-footer row">
                    <small class="pr-2"><strong>Category:</strong><?php echo $story['cat_name']; ?></small>
                    <small class="pr-2"><strong>Date:</strong> <i><?php echo $story['reg_date']; ?></i></small>
                    <small class="pr-2"><strong>Author</strong> <?php echo $user['name']; ?></small>
                    <small class="pr-2">
                      <strong>status:</strong>
                      <?php if( $story['status'] == 0) : ?>
                        <span class="badge bg-warning">Pending till review</span>
                      <?php elseif($story['image'] == 1) : ?>
                        <span class="badge bg-primary">Published</span>
                      <?php elseif($story['status'] == 2) : ?>
                        <span class="badge bg-danger">Rejected</span>
                      <?php endif; ?> 
                    </small>
                    <small>
                        <strong>Location:</strong>
                        <i class=""><?php echo $story['loca_country'] ?></i>
                    </small>
                  </div>
                  <hr>
                   <p class="card-text">
                      <?php echo htmlspecialchars_decode(stripslashes($story['story'])) ?>
                   </p>
                  
                </div>
              </div>
          </div>
        </div><!-- /.box -->
    </div>
</div>