<?php 

if(isset($_GET['story'])){
    if(!empty($_GET['story'])){
        //get user from model
        $stories = getAllStory($_GET['story']);
        //fetch story from model function getstories
        // $stories = getStories($user['id']);
    }
}
$stories = getAllStory();
$categories = getAllCategories();
$locations = getAllLocations();

?>

<br><br>
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="card mt-3">
            <div class="card-header">
                <h5 class="card-title">All Category</h5>
                <small class="text-muted">Total number of story in a category on the right</small>
            </div>

            <div class="card-body">
                <div class="list-group">
                    <a href="?page=stories" class="list-group-item list-group-item-action active">
                        All Categories
                    </a>
                    <?php foreach($categories as $category) : ?>
                        <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <?php echo $category['name']; ?>
                            <span class="badge badge-primary badge-pill">
                            <?php echo count(getstorybyCategory($category['id'])) ; ?>
                            </span>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <h5 class="card-title">All Locations</h5>
                <small class="text-muted">See stories about a location</small>
            </div>

            <div class="card-body">
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                        All Locations
                    </a>
                    <?php foreach($locations as $location) : ?>
                        <a href="{{route('all.story', ['location'=>$location->id])}}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <?php echo $location['country']; ?>
                            <span class="badge badge-primary badge-pill">
                            <?php echo count(getAllLocations($category['id'])) ; ?>
                            </span>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
      </div>
        <div class="col-md-9">
            <div class="row">
                <?php foreach($stories as $story) : ?>
                    <div class="col-md-6 card my-3" style="height: 220px; background-image: url('<?php echo $story['image']; ?>');background-position: center;background-repeat: no-repeat; background-size: cover;">

                        <div class="d-flex justify-content-center align-items-end card-body">
                            <div class="card-title px-4" style="width: 70%; height: 190px; background-color: rgb(0,0,0, 0.5); color: #fff; border-radius: 10px;" >
                                <h3 class="text-center"><?php echo $story['title'] ?></h3>
                                <p>
                                    <?php echo html_entity_decode(substr(strip_tags($story['story']) , 0, 50)); ?>
                                </p>
                                <p class="d-flex justify-content-center">
                                    <a class="btn btn-primary btn-sm" href="#">Read story</a>
                                </p>
                                <br>
                            </div>
                        </div>
        
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
  </div>
</div>