<?php
	if(isset($_GET['access'])){
		if(!empty($_GET['access'])){
			//get user from model
			$user = checkAccess($_GET['access']);
			//fetch story from model function getstories
			$stories = getStories($user['id']);
		}
	}

    if($_SERVER["REQUEST_METHOD"] == "POST"){
        $postData['title'] = $_POST['title'];
        $postData['category_id'] = $_POST['category_id'];
        $postData['location_id'] = $_POST['location_id'];
        $postData['story'] = $_POST['story'];
        $postData['user_id'] = $user['id'];
        $postData['image'] = $_FILES["story_image"];
        
        createStory($postData);
    }

    // return var_dump(getstoriesFull($user['id']));
?> 

<div class="content">
    
    <div class="container">
        <?php if(!empty($success)) : ?> 
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button> 
                <strong><?php echo $success; ?></strong>
            </div>
        <?php endif; ?>

        <?php if(!empty($error)) : ?> 
            <div class="alert alert-danger alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button> 
                <strong><?php echo $error; ?></strong>
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-lg-12">
                <div class="card mt-3">
                    <div class="card-header row">
                        <h3 class="card-title col-md-10">All My Stories</h3>
                        <button data-target="#modal-lg" data-toggle="modal" class="col-md-2 btn btn-sm btn-primary">Add new Story</button>
                    </div>
                    <div class="modal fade" id="modal-lg" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Share your story to the world</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                <form method="post" class="profile-wrapper" enctype="multipart/form-data" action="<?php $config['VIEW_PATH']. $page . '.phtml'; ?>" >
                                        <div class="form-group">
                                        <label for="fname">Story Title</label>                     
                                        <input class="form-control" type="text" name="title" required autofocus placeholder="Super Hikcing Experience">
                                    </div> 
                                    <div class="form-group">
                                            <label for="fname">Story Category</label> 
                                            <select class="form-control" name="category_id" id="">
                                                <optgroup label="Other countries">
                                                    <?php foreach ($categories = getAllCategories() as $category) : ?>
                                                        <option value="<?php echo $category['id']; ?>"><?php echo $category['name']; ?></option>
                                                    <?php endforeach ?>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="fname">Select Location</label> 
                                            <select class="form-control" name="location_id" id="">
                                                <optgroup label="Other countries">
                                                    <?php foreach ($locations = getAllLocations() as $location) : ?>
                                                                <option value="<?php echo $location['id']; ?>"><?php echo $location['country']; ?></option>
                                                    <?php endforeach ?>
                                                </optgroup>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="fname">Main Story</label>
                                            <textarea  class="form-control" id="storyEditor" rows="50" cols="40" name="story">
                                            </textarea>
                                            <script>
                                                // Replace the <textarea id="editor1"> with a CKEditor
                                                // instance, using default configuration.
                                                CKEDITOR.replace( 'storyEditor' );
                                            </script>   
                                        </div>
                
                                        <div class="form-group">
                                            <label for="featured_image">Featured Image</label>
                                            <input class="form-control" type="file" name="story_image" required autofocus>  
                                        </div>
                                    </div>
                                    <div class="modal-footer justify-content-between">
                                        <input hidden type="text" name="is_draft" value="1">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
                                        <button type="submit" class="btn btn-primary">Publish</button>
                                    </div>

                            </form>
                        </div>
                    </div>
                </div>
            
                <div class="card-body">
                    <div class="row">
                        <?php if(count(getstoriesFull($user['id'])) > 0 ) : ?>
                            <?php foreach($stories = getstoriesFull($user['id']) as $story) : ?>
                                <div class="col-md-4 col-sm-6 col-xs-12">
                                    <div class="card card-widget widget-user shadow-lg">
                                        <div class="widget-user-header text-white"
                                        style="background: url('<?php echo $story['image']; ?>') center center;">
                                        </div>
                                        <div class="widget-user-image">
                                            <?php if(isset($user['image'])) : ?>
                                                <img class="img-circle" src="<?php echo $user['image']; ?>" alt="User Avatar">
                                            <?php else : ?>
                                                <img class="img-circle" src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg" alt="User Avatar">
                                            <?php endif; ?>
                                        </div>
                                        <div class="card-footer">
                                            <div class="row">
                                                <div class="justify-content-center">
                                                    <h4 class="widget-user-desc text-center">
                                                    <?php echo $story['title']; ?></h4> 
                                                </div>
                                                <div class="row">
                                                    <p class="row px-3">
                                                        <?php echo substr(strip_tags($story['story']) , 0, 100); ?> ..
                                                    </p>
                                                    <div class="row px-3">
                                                        <small class="pr-4">
                                                            <strong>Category:</strong>
                                                            <?php echo $story['cat_name']; ?>
                                                        </small>
                                                        <small>
                                                            <strong>Date:</strong>
                                                            <i>
                                                                <?php echo $story['reg_date']; ?>
                                                            </i>
                                                        </small>
                                                        <small class="pr-4">
                                                            <strong>status:</strong>
                                                            <?php if($story['status'] == 0) : ?>
                                                            <span class="badge badge-warning">Pending till review</span>
                                                            <?php elseif($story['status'] == 1) : ?>
                                                            <span class="badge badge-primary">Published</span>
                                                            <?php elseif($story['status'] == 2) : ?>
                                                                <span class="badge badge-danger">Rejected</span>
                                                            <?php endif; ?>
                                                        
                                                        </small>
                                                        <small>
                                                            <strong>Location:</strong>
                                                            <i class=""><?php echo $story['loca_country']?></i>
                                                        </small>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="row gx-3">
                                                <a href="?page=user_preview&id=<?php echo $story['id']; ?>&access=xantha982" class="btn btn-xs btn-primary mx-2 px-2">Preview</a>
                                                <?php if($user['role'] == 1) : ?>
                                                    <a href="" data-target="#editor<?php echo $story['id']; ?>" data-toggle="modal" class="btn btn-xs btn-warning mx-2 px-2">Take Action</a>
                                                <?php else : ?>
                                                    <a href="" data-target="#editor<?php echo $story['id']; ?>" data-toggle="modal" class="btn btn-xs btn-default mx-2 px-2">Edit</a>
                                                <?php endif; ?>

                                                <?php if($user['role'] == 1) : ?>

                                                    <a href="#"
                                                    onclick="event.preventDefault();
                                                    document.getElementById('del-story2$story->id').submit();" class="btn btn-xs btn-danger mx-2 px-2">Delete</a>
                                        
                                                    <form id="del-story2<?php echo $story['id']; ?>" action="#" method="POST" style="display: none;">
                                                    </form>
                                                <?php else: ?>
                                                    <a href="{{ route('delete.story', ['id' => $story->id]) }}"
                                                    onclick="event.preventDefault();
                                                    document.getElementById('del-story1$story->id').submit();" class="btn btn-xs btn-danger mx-2 px-2">Delete</a>
                                            
                                                    <form id="" action="#" method="POST" style="display: none;">
                                                    </form>
                                                <?php endif; ?>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="modal fade" id="editor<?php echo $story['id']; ?>" aria-hidden="true">
                                        <div class="modal-dialog modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Share your story to the world</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <?php if($user['role'] == 1) : ?>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="d-flex justify-content-center">
                                                                    <form method="Post" class="profile-wrapper" action="" >
                                                                        
                                                                        <div class="modal-footer justify-content-between">
                                                                        <input hidden type="text" name="approve" value="1">
                                                                        <button type="submit" class="btn btn-success">Approve story</button>
                                                                        </div>
                                                
                                                                    </form>
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="d-flex justify-content-center">
                                                                    <form method="post" class="profile-wrapper" enctype="multipart/form-data" action="" >
                                                                        <div class="modal-footer justify-content-between">
                                                                        <input hidden type="text" name="reject" value="2">
                                                                        <button type="submit" class="btn btn-danger">Reject story</button>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    <?php else: ?>
                                                        <form method="post" class="profile-wrapper" enctype="multipart/form-data" action="" >
                                                            <div class="form-group">
                                                                <label for="fname">Story Title</label>                     
                                                                <input class="form-control" value="<?php echo $story['title']; ?>" type="text" name="title" required autofocus placeholder="Super Hikcing Experience">
                                                            </div> 
                                                            <div class="form-group">
                                                                <label for="fname">Story Category</label> 
                                                                <select class="form-control" name="category" id="">
                                                                    <option selected value="<?php echo $story['cat_id']; ?>"><?php echo $story['cat_name']; ?></option>
                                                                    <optgroup label="Other countries">
                                                                        <?php foreach ($categories = getAllCategories() as $category) : ?>
                                                                            <option value="<?php echo $category['id']; ?>"><?php echo $category['name']; ?></option>
                                                                        <?php endforeach ?>
                                                                    </optgroup>
                                                                </select>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="fname">Select Location</label> 
                                                                <select class="form-control" name="location" id="">
                                                                    <option selected value="<?php echo $story['loca_id']; ?>">
                                                                        <?php echo $story['loca_country'] ?>
                                                                    </option>
                                                                    <optgroup label="Other countries">
                                                                        <?php foreach ($locations = getAllLocations() as $location) : ?>
                                                                                    <option value="<?php echo $location['id']; ?>"><?php echo $location['country']; ?></option>
                                                                        <?php endforeach ?>
                                                                    </optgroup>
                                                                </select>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="fname">Main Story</label>
                                                                <textarea  class="form-control" id="storyEditor<?php echo $story['id'] ?>" rows="50" cols="40" name="story">
                                                                    <?php echo $story['story'] ?>
                                                                </textarea>
                                                                <script>
                                                                    // Replace the <textarea id="editor1"> with a CKEditor
                                                                    // instance, using default configuration.
                                                                    CKEDITOR.replace( 'storyEditor<?php echo $story['id'] ?>');
                                                                </script>   
                                                            </div>
                                                            <div class="form-group">
                                                                <?php if($story['image'] != null) : ?>
                                                                    <label for="image_preview">Image preview</label><br>
                                                                    <img style="width:100%; height: 400%;" src="<?php echo $story['image']; ?>" alt="">
                                                                <?php else: ?>
                                                                    <p>No image available </p>
                                                                <?php endif ?>
                                                            </div>
                                                            <div class="form-group">
                                                            <label for="featured_image">Featured Image</label>
                                                            <input class="form-control" type="file" name="featured_image" >  
                                                            </div> 
                                                            <div class="modal-footer justify-content-between">
                                                            <input hidden type="text" name="is_draft" value="1">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
                                                            <button type="submit" class="btn btn-primary">Send for review</button>
                                                            </div>
                                                        </form>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <p class="text-center">You have no stories yet, create one today!</p>
                        <?php endif; ?>
                    </div>
                </div>

                </div>    
            </div>
        </div>
        
    </div>
</div>

