 
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="assets/admin-assets/plugins/jquery/jquery.min.js"></script>
    
    <!-- Bootstrap 4 -->
    <script src="assets/admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="assets/admin-assets/dist/js/adminlte.min.js"></script>


    <!--custom-->
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

    <script>
        function myFunction() {
          var x = document.getElementById("mySelect").value;
          if (x=='archive') {
            document.getElementById('archive').style.display = 'block';
            document.getElementById('new').style.display = 'none';
          }

          if (x=='new') {
            document.getElementById('new').style.display = 'block';
            document.getElementById('archive').style.display = 'none';
          }

        }

        function eyeFunction() {
          var x = document.getElementById("mySelectEye").value;
          if (x=='Yes') {
            document.getElementById('eye').style.display = 'block'; 
          }
          else{
            document.getElementById('eye').style.display = 'none';
          }
        }

        function disabilityFunction() {
          var x = document.getElementById("mySelectDisability").value;
          if (x=='Yes') {
            document.getElementById('disability').style.display = 'block'; 
          }
          else{
            document.getElementById('disability').style.display = 'none';
          }
        }
    </script>

  </body>
</html>
