<!-- Main Sidebar Container -->
<?php
	if(isset($_GET['access'])){
		if(!empty($_GET['access'])){
			//get user from model
			$user = checkAccess($_GET['access']);
			//fetch story from model function getstories
			$stories = getStories($user['id']);
		}

	}

?>
<aside class="main-sidebar sidebar-dark-primary elevation-4">
	<a href="/" class="brand-link">
	  
	  <span class="brand-text text-white text-center" style="font-size: 14px;font-weight: bolder; text-transform: uppercase;">
		Afrib Design
	  </span>
	</a>

	<!-- Sidebar -->

	<div class="sidebar">
	  <div class="user-panel mt-3 pb-3 mb-3 d-flex">
		<div class="image">
            <?php if(isset($user['image'])) : ?> 
                <div class="d-flex justify-content-center">
					<img width="160px" height="160px" class="img-circle" src="<?php echo $user['image']; ?>" alt="Card image cap">
				</div>
            <?php else: ?>
			<div class="d-flex justify-content-center">
				<img class="img-circle" width="160px" height="160px" src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg" alt="User Avatar">
			</div>
            <?php endif; ?>
		</div>
		<div class="info">
		  <span class="p-1 text-white">
            <?php echo $user['username']; ?>
		  </span>
		  <span class="dot text-green"></span>
		</div>
	  </div>

	  <!-- Sidebar Menu -->
	  <nav class="mt-2">
		<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
		    <li class="nav-item">
                <?php if($user['role'] == 1) : ?> 
                    <a href="?page=user_dashboard&access=xantha982" class="nav-link">
                        <i class="nav-icon fa fa-th text-white"></i>
                        <p>
                        Dashboard
                        </p>
                    </a>
                <?php else: ?>
                    <a href="?page=user_dashboard&access=xantha982" class="nav-link">
                        <i class="nav-icon fa fa-th text-white"></i>
                        <p>
                        Dashboard
                        </p>
                    </a>
                <?php endif; ?>
		    </li>
		  <li class="nav-item has-treeview">
			  <a href="#" class="nav-link">
				<i class="nav-icon fa fa-edit text-yellow"></i>
                    <?php if($user['role'] == 1) : ?> 
                        <p>
                            All Stories
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    <?php else: ?>
                        <p>
                            My Stories
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    <?php endif; ?>
				
			  </a>
			  <ul class="nav nav-treeview">
                <?php if($user['role'] == 1) : ?> 
					<li class="nav-item">
						<a href="" class="nav-link ml-3">
						<i class="far fa-circle nav-icon"></i>
						<p>All Stories</p>
						</a>
				   </li>
					<li class="nav-item">
						<a href="#" class="nav-link ml-3">
							<i class="far fa-circle nav-icon"></i>
							<p>Story Categories</p>
						</a>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link ml-3">
							<i class="far fa-circle nav-icon"></i>
							<p>Story Location</p>
						</a>
					</li>
				<?php else: ?>
				  <li class="nav-item">
                        <a href="?page=user_stories&access=xantha982" class="nav-link ml-3">
                        <i class="far fa-circle nav-icon"></i>
                        <p>All Stories</p>
                        </a>
				  </li>
				<?php endif; ?>

			  </ul>
		  </li>
            <?php if($user['role'] == 0) : ?> 
		  
                <li class="nav-item">
                    <a href="?page=user_profile&access=xantha982" class="nav-link">
                        <i class="nav-icon fa fa-product-hunt text-yellow"></i>
                        <p>Profile</p>
                    </a>
                </li>
			<?php else: ?>

                <li class="nav-item">
                    <a href="?page=admin_settings&access=xantha982" class="nav-link">
                    <i class="nav-icon fa fa-cogs text-pink"></i>
                    <p>Setting</p>
                    </a>
                </li>
            
			<?php endif ?>
		  
		  <li class="nav-item">
			<a class="nav-link" href="#"
			  onclick="event.preventDefault();
			  document.getElementById('logout-form').submit();">
			  <i class="nav-icon fa fa-power-off text-red"></i>
			  <p>Logout</p>
			</a>

			<form id="logout-form" action="#" method="POST" style="display: none;">
			</form>
		  </li>
		</ul>
	  </nav>
	  <!-- /.sidebar-menu -->
	</div>

	<!-- /.sidebar -->

</aside>