
	<footer class="bg-dark mt-5">
		<div class="container">
			<div class="mt-4 pa-4 text-center text-white">
				<strong>Afrib Design <?php echo date('Y') ?> All rights reserved</strong>
			</div>
		</div>
	</footer>
	<!-- Bootstrap JS -->
	<script src="assets/js/bootstrap.bundle.min.js"></script>
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Template Functions -->
	<script src="assets/js/functions.js"></script>
</body>
