
<!DOCTYPE html>
<html lang="en">
 
<head>
	<title><?php echo (isset($title) ? $title : 'Not found') ;  ?> - Afrib Design</title>
	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="Webestica.com">
	<meta name="description" content="Bootstrap based News, Magazine and Blog Theme">


    <link rel="icon" type="image/png" sizes="16x16" href="#">

	<link rel="stylesheet" type="text/css" href="assets/fonts/font-awesome/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="assets/fonts/bootstrap-icons/bootstrap-icons.css">

	<!-- Theme CSS -->
	<link id="style-switch" rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
	<link id="style-switch" rel="stylesheet" type="text/css" href="assets/css/bootstrap-utilities.min.css">
	<link id="style-switch" rel="stylesheet" type="text/css" href="assets/css/bootstrap-grid.min.css">

</head>
<body>
