<header>
	<nav class="navbar navbar-expand-lg navbar-light shadow-sm" style="background: #f4f4f4;">
		<div class="container">
			<a class="navbar-brand pr-5" href="/"><h3>Afrib Design</h3></a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="?page=home">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="?page=stories">Stories</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="?page=contact">Contact Us</a>
			</li>
			</ul>
			<div class="d-flex">
				<a class="btn btn-primary" href="?page=register">Join Us</a>
			</div>
		</div>
		</div>
	</nav>
</header>
